extends:
 - stylelint-config-recommended
 - stylelint-config-recommended-scss
 - stylelint-prettier/recommended
 - stylelint-config-prettier # Last to override other presets that conflict with Prettier
plugins:
  - stylelint-scss